### ISSUE TITLE
Top priority issues

### ISSUE THREAD

**Issue by linucksrox** [linucksrox/Textecutor#20]
Resolve these before initial release:
- [ ] #7 Main screen should be a simple overview of actions
- [ ] #8 Check and re-check permissions at key times
- [ ] #17 Full volume action should reset volume to previous setting after a timeout
- [ ] #5 Get a better icon
- [ ] #10 Getting started page should walk you through what the app does
